# Generated by cpp11: do not edit by hand

marquee_c <- function(text, styles, ignore_html) {
  .Call(`_marquee_marquee_c`, text, styles, ignore_html)
}

place_bullets <- function(type, indent, block, string_is_empty, bullet_number, bullets) {
  .Call(`_marquee_place_bullets`, type, indent, block, string_is_empty, bullet_number, bullets)
}
