# Generated by cpp11: do not edit by hand

marquee_c <- function(text, styles) {
  .Call(`_marquee_marquee_c`, text, styles)
}

place_bullets <- function(type, indent, string_is_empty, bullet_number, bullets) {
  .Call(`_marquee_place_bullets`, type, indent, string_is_empty, bullet_number, bullets)
}

block_is_last <- function(indentation) {
  .Call(`_marquee_block_is_last`, indentation)
}
